version: 2
jobs:
  build:
    working_directory: ~/Streampunk/codecadon
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      UV_THREADPOOL_SIZE: 16
    docker:
    - image: circleci/node:8
      command: /sbin/init
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
    - run: npm install
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ./node_modules
    - run: echo 'export PATH="~/Streampunk/codecadon/node_modules/.bin:$PATH"' >> $BASH_ENV
    - run: mkdir -p $CIRCLE_ARTIFACTS/tap
    - run: mkdir -p $CIRCLE_TEST_REPORTS/junit
    - run: tap -R xunit -o /tmp/circleci-test-results/tap/results.tap test/*.js > /tmp/circleci-test-results/junit/results.xml
      
    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
